import type { KeyDef } from "./types.js";

export const EVDEV_KEYCODES: KeyDef[] = [
  { name: "ESC", code: 9 },
  { name: "AE01", code: 10 },
  { name: "AE02", code: 11 },
  { name: "AE03", code: 12 },
  { name: "AE04", code: 13 },
  { name: "AE05", code: 14 },
  { name: "AE06", code: 15 },
  { name: "AE07", code: 16 },
  { name: "AE08", code: 17 },
  { name: "AE09", code: 18 },
  { name: "AE10", code: 19 },
  { name: "AE11", code: 20 },
  { name: "AE12", code: 21 },
  { name: "BKSP", code: 22 },
  { name: "TAB", code: 23 },
  { name: "AD01", code: 24 },
  { name: "AD02", code: 25 },
  { name: "AD03", code: 26 },
  { name: "AD04", code: 27 },
  { name: "AD05", code: 28 },
  { name: "AD06", code: 29 },
  { name: "AD07", code: 30 },
  { name: "AD08", code: 31 },
  { name: "AD09", code: 32 },
  { name: "AD10", code: 33 },
  { name: "AD11", code: 34 },
  { name: "AD12", code: 35 },
  { name: "RTRN", code: 36 },
  { name: "LCTL", code: 37 },
  { name: "AC01", code: 38 },
  { name: "AC02", code: 39 },
  { name: "AC03", code: 40 },
  { name: "AC04", code: 41 },
  { name: "AC05", code: 42 },
  { name: "AC06", code: 43 },
  { name: "AC07", code: 44 },
  { name: "AC08", code: 45 },
  { name: "AC09", code: 46 },
  { name: "AC10", code: 47 },
  { name: "AC11", code: 48 },
  { name: "TLDE", code: 49 },
  { name: "LFSH", code: 50 },
  { name: "BKSL", code: 51 },
  { name: "AB01", code: 52 },
  { name: "AB02", code: 53 },
  { name: "AB03", code: 54 },
  { name: "AB04", code: 55 },
  { name: "AB05", code: 56 },
  { name: "AB06", code: 57 },
  { name: "AB07", code: 58 },
  { name: "AB08", code: 59 },
  { name: "AB09", code: 60 },
  { name: "AB10", code: 61 },
  { name: "RTSH", code: 62 },
  { name: "KPMU", code: 63 },
  { name: "LALT", code: 64 },
  { name: "SPCE", code: 65 },
  { name: "CAPS", code: 66 },
  { name: "FK01", code: 67 },
  { name: "FK02", code: 68 },
  { name: "FK03", code: 69 },
  { name: "FK04", code: 70 },
  { name: "FK05", code: 71 },
  { name: "FK06", code: 72 },
  { name: "FK07", code: 73 },
  { name: "FK08", code: 74 },
  { name: "FK09", code: 75 },
  { name: "FK10", code: 76 },
  { name: "NMLK", code: 77 },
  { name: "SCLK", code: 78 },
  { name: "KP7", code: 79, aliases: ["KP07"] },
  { name: "KP8", code: 80, aliases: ["KP08"] },
  { name: "KP9", code: 81, aliases: ["KP09"] },
  { name: "KPSU", code: 82 },
  { name: "KP4", code: 83, aliases: ["KP04"] },
  { name: "KP5", code: 84, aliases: ["KP05"] },
  { name: "KP6", code: 85, aliases: ["KP06"] },
  { name: "KPAD", code: 86 },
  { name: "KP1", code: 87, aliases: ["KP01"] },
  { name: "KP2", code: 88, aliases: ["KP02"] },
  { name: "KP3", code: 89, aliases: ["KP03"] },
  { name: "KP0", code: 90, aliases: ["KP00"] },
  { name: "KPDL", code: 91 },
  { name: "LSGT", code: 94 },
  { name: "FK11", code: 95 },
  { name: "FK12", code: 96 },
  { name: "LVL3", code: 97, aliases: ["AB11", "LMTA"] },
  { name: "LMTA", code: 125 },
  { name: "RMTA", code: 126 },
  { name: "KPEN", code: 98 },
  { name: "RCTL", code: 97 },
  { name: "KPDV", code: 98 },
  { name: "RALT", code: 100 },
  { name: "HOME", code: 102 },
  { name: "UP", code: 103 },
  { name: "PGUP", code: 104 },
  { name: "LEFT", code: 105 },
  { name: "RGHT", code: 106 },
  { name: "END", code: 107 },
  { name: "DOWN", code: 108 },
  { name: "PGDN", code: 109 },
  { name: "INS", code: 110 },
  { name: "DELE", code: 111 },
  { name: "PAUS", code: 119 },
  { name: "COMP", code: 127 },
];

export const US_LAYOUT: Record<string, (string | number)[][]> = {
  ESC: [["Escape"]],
  AE01: [["1", "exclam"], ["bar"]],
  AE02: [["2", "at"]],
  AE03: [["3", "numbersign"]],
  AE04: [["4", "dollar"], ["EuroSign"]],
  AE05: [["5", "percent"], ["EuroSign"]],
  AE06: [["6", "asciicircum"]],
  AE07: [["7", "ampersand"]],
  AE08: [["8", "asterisk"]],
  AE09: [["9", "parenleft"]],
  AE10: [["0", "parenright"]],
  AE11: [["minus", "underscore"]],
  AE12: [["equal", "plus"]],
  BKSP: [["BackSpace"]],
  TAB: [["Tab"]],
  AD01: [["q", "Q"]],
  AD02: [["w", "W"]],
  AD03: [["e", "E"]],
  AD04: [["r", "R"]],
  AD05: [["t", "T"]],
  AD06: [["y", "Y"]],
  AD07: [["u", "U"]],
  AD08: [["i", "I"]],
  AD09: [["o", "O"]],
  AD10: [["p", "P"]],
  AD11: [["bracketleft", "braceleft"]],
  AD12: [["bracketright", "braceright"]],
  RTRN: [["Return"]],
  LCTL: [["Control_L"]],
  AC01: [["a", "A"]],
  AC02: [["s", "S"]],
  AC03: [["d", "D"]],
  AC04: [["f", "F"]],
  AC05: [["g", "G"]],
  AC06: [["h", "H"]],
  AC07: [["j", "J"]],
  AC08: [["k", "K"]],
  AC09: [["l", "L"]],
  AC10: [["semicolon", "colon"]],
  AC11: [["apostrophe", "quotedbl"]],
  TLDE: [["grave", "asciitilde"]],
  LFSH: [["Shift_L"]],
  BKSL: [["backslash", "bar"]],
  AB01: [["z", "Z"]],
  AB02: [["x", "X"]],
  AB03: [["c", "C"]],
  AB04: [["v", "V"]],
  AB05: [["b", "B"]],
  AB06: [["n", "N"]],
  AB07: [["m", "M"]],
  AB08: [["comma", "less"]],
  AB09: [["period", "greater"]],
  AB10: [["slash", "question"]],
  RTSH: [["Shift_R"]],
  KPMU: [["KP_Multiply"]],
  LALT: [["Alt_L"]],
  SPCE: [["space"]],
  CAPS: [["Caps_Lock"]],
  FK01: [["F1"]],
  FK02: [["F2"]],
  FK03: [["F3"]],
  FK04: [["F4"]],
  FK05: [["F5"]],
  FK06: [["F6"]],
  FK07: [["F7"]],
  FK08: [["F8"]],
  FK09: [["F9"]],
  FK10: [["F10"]],
  NMLK: [["Num_Lock"]],
  SCLK: [["Scroll_Lock"]],
  KP7: [["KP_7"]],
  KP8: [["KP_8"]],
  KP9: [["KP_9"]],
  KPSU: [["KP_Subtract"]],
  KP4: [["KP_4"]],
  KP5: [["KP_5"]],
  KP6: [["KP_6"]],
  KPAD: [["KP_Add"]],
  KP1: [["KP_1"]],
  KP2: [["KP_2"]],
  KP3: [["KP_3"]],
  KP0: [["KP_0"]],
  KPDL: [["KP_Decimal"]],
  LSGT: [["less", "greater"], ["bar"]],
  FK11: [["F11"]],
  FK12: [["F12"]],
  LVL3: [["ISO_Level3_Shift"]],
  KPEN: [["KP_Enter"]],
  RCTL: [["Control_R"]],
  KPDV: [["KP_Divide"]],
  RALT: [["Alt_R"]],
  HOME: [["Home"]],
  UP: [["Up"]],
  PGUP: [["Page_Up"]],
  LEFT: [["Left"]],
  RGHT: [["Right"]],
  END: [["End"]],
  DOWN: [["Down"]],
  PGDN: [["Page_Down"]],
  INS: [["Insert"]],
  DELE: [["Delete"]],
  PAUS: [["Pause"]],
  COMP: [["Menu"]],
  LMTA: [["Super_L"]],
  RMTA: [["Super_R"]],
};

export const COMMON_KEY_TYPES = [
  {
    name: "ONE_LEVEL",
    levelNames: [{ name: "Any" }],
    modifiers: [],
    map: [],
  },
  {
    name: "TWO_LEVEL",
    levelNames: [{ name: "Base" }, { name: "Shift" }],
    modifiers: ["Shift"],
    map: [{ modifiers: ["Shift"], level: 2 }],
  },
  {
    name: "ALPHABETIC",
    levelNames: [{ name: "Base" }, { name: "Shift" }],
    modifiers: ["Shift", "Lock"],
    map: [
      { modifiers: ["Shift"], level: 2 },
      { modifiers: ["Lock"], level: 2 },
      { modifiers: ["Shift", "Lock"], level: 1 },
    ],
  },
  {
    name: "FOUR_LEVEL",
    levelNames: [
      { name: "Base" },
      { name: "Shift" },
      { name: "Alt" },
      { name: "Shift+Alt" },
    ],
    modifiers: ["Shift", "Mod5"],
    map: [
      { modifiers: ["Shift"], level: 2 },
      { modifiers: ["Mod5"], level: 3 },
      { modifiers: ["Shift", "Mod5"], level: 4 },
    ],
  },
  {
    name: "FOUR_LEVEL_ALPHABETIC",
    levelNames: [
      { name: "Base" },
      { name: "Shift" },
      { name: "Alt" },
      { name: "Shift+Alt" },
    ],
    modifiers: ["Shift", "Lock", "Mod5"],
    map: [
      { modifiers: ["Shift"], level: 2 },
      { modifiers: ["Lock"], level: 2 },
      { modifiers: ["Shift", "Lock"], level: 1 },
      { modifiers: ["Mod5"], level: 3 },
      { modifiers: ["Shift", "Mod5"], level: 4 },
      { modifiers: ["Lock", "Mod5"], level: 4 },
      { modifiers: ["Shift", "Lock", "Mod5"], level: 3 },
    ],
  },
  {
    name: "FOUR_LEVEL_SEMICOLON",
    levelNames: [
      { name: "Base" },
      { name: "Shift" },
      { name: "Alt" },
      { name: "Shift+Alt" },
    ],
    modifiers: ["Shift", "Mod5"],
    map: [
      { modifiers: ["Shift"], level: 2 },
      { modifiers: ["Mod5"], level: 3 },
      { modifiers: ["Shift", "Mod5"], level: 4 },
    ],
  },
  {
    name: "KEYPAD",
    levelNames: [{ name: "Base" }, { name: "NumLock" }],
    modifiers: ["Mod2"],
    map: [{ modifiers: ["Mod2"], level: 2 }],
  },
  {
    name: "FOUR_LEVEL_KEYPAD",
    levelNames: [
      { name: "Base" },
      { name: "NumLock" },
      { name: "Alt" },
      { name: "NumLock+Alt" },
    ],
    modifiers: ["Mod2", "Mod5"],
    map: [
      { modifiers: ["Mod2"], level: 2 },
      { modifiers: ["Mod5"], level: 3 },
      { modifiers: ["Mod2", "Mod5"], level: 4 },
    ],
  },
];
